server:
  port: 8088

spring:
  application:
    name: ms-envio
  datasource:
    url: jdbc:mysql://localhost:3306/db_envio?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog.sql