server:
  port: 9090

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: cliente-service
          uri: http://cliente-service:9091
          predicates:
            - Path=/api/v1/clientes/**
            
        - id: ms-producto
          uri: http://ms-producto:8081
          predicates:
            - Path=/api/v1/productos/**, /api/v1/categorias/**
            
        - id: ms-carrito
          uri: http://ms-carrito:8084
          predicates:
            - Path=/api/v1/carrito/**
            
        - id: ms-pedido
          uri: http://ms-pedido:9094
          predicates:
            - Path=/api/v1/pedidos/**
            
        - id: ms-transaccion
          uri: http://ms-transaccion:8085
          predicates:
            - Path=/api/v1/transacciones/**
            
        - id: ms-envio
          uri: http://ms-envio:8086  # Asegura el puerto que definiste
          predicates:
            - Path=/api/v1/envios/**
            
        - id: ms-descuento
          uri: http://ms-descuento:8088 # Asegura el puerto que definiste
          predicates:
            - Path=/api/v1/descuentos/**
            
        - id: ms-resena
          uri: http://ms-resena:8087
          predicates:
            - Path=/api/v1/resenas/**
            
        - id: ms-inventario
          uri: http://ms-inventario:8089 # Asegura el puerto que definiste
          predicates:
            - Path=/api/v1/inventario/**
            
        - id: ms-facturacion
          uri: http://ms-facturacion:8092 # Asegura el puerto que definiste
          predicates:
            - Path=/api/v1/facturas/**